<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Business logic for recording payments, refunds, and voids against a
 * fee record (Step 7.7).
 *
 * @package   local_financedepartment
 * @copyright 2026 Wunna
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_financedepartment;

defined('MOODLE_INTERNAL') || die();

/**
 * Class feepayment_manager
 *
 * Every financedep_feepayment row is either a PAYMENT (money coming in,
 * increases financedep_feerecord.paidamount) or a REFUND (money going
 * back out, decreases it) - never a signed amount column, the sign comes
 * from paymenttype. void_payment() below reverses whichever effect an
 * ACTIVE row had, then marks it VOID; it never deletes a row, matching
 * this plugin's "financial history is never destroyed" pattern used
 * throughout (scholarship/discount approvals, installment cancellation).
 *
 * 2026-09-09 scope decisions confirmed with the user before building
 * (see [[financedepartment-schema]] project memory for the full
 * discussion): (1) linking a payment to a specific installment
 * (financedep_feepayment.installmentschedid) is OPTIONAL - a payment can
 * always be recorded against the fee record as a whole with no
 * installment plan involved at all; (2) recording a refund is a DIRECT,
 * instant entry (like recording a normal payment), not a
 * request-and-approve workflow like scholarships/discounts - so there is
 * deliberately no get_pending()/review-queue method in this class;
 * (3) voiding an existing payment requires the higher-trust
 * `managerefunds` capability (same as issuing a refund), not the
 * lower-trust `recordpayments` capability that recording a normal
 * payment needs - see db/access.php. This class itself does not check
 * capabilities (matching every other manager in this plugin); that is
 * the calling page's job via access_manager::require_manage().
 *
 * Receipt numbers (financedep_feepayment.receiptnumber, UNIQUE) are
 * SYSTEM-GENERATED by generate_receipt_number() below, not typed in by
 * finance staff - this was a discretionary implementation choice (the
 * user was not asked specifically), made to avoid duplicate-receipt-
 * number validation errors during data entry. If the user later wants
 * staff to enter their own receipt book numbers instead, this is the
 * method to revisit.
 */
class feepayment_manager {

    /**
     * Returns one payment with fee record/student/category/linked-
     * installment details joined in, or false if not found.
     *
     * @param int $id
     * @return \stdClass|false
     */
    public static function get(int $id) {
        global $DB;

        $sql = "SELECT p.*, r.studentid, r.balance AS feerecordbalance, r.status AS feerecordstatus,
                       u.firstname, u.lastname, u.email,
                       f.academicyear, cc.name AS categoryname,
                       s.installmentnumber, s.duedate AS installmentduedate,
                       vu.firstname AS voidedbyfirstname, vu.lastname AS voidedbylastname
                  FROM {financedep_feepayment} p
                  JOIN {financedep_feerecord} r ON r.id = p.feerecordid
                  JOIN {user} u ON u.id = r.studentid
                  JOIN {financedep_feestructure} f ON f.id = r.feestructureid
                  JOIN {course_categories} cc ON cc.id = f.categoryid
             LEFT JOIN {financedep_installmentsched} s ON s.id = p.installmentschedid
             LEFT JOIN {user} vu ON vu.id = p.voidedby
                 WHERE p.id = :id";

        $record = $DB->get_record_sql($sql, ['id' => $id]);
        if (!$record) {
            return false;
        }

        $record->fullname = fullname($record);

        return $record;
    }

    /**
     * Returns every payment/refund recorded against one fee record,
     * newest first, with the linked installment's number (if any) joined
     * in - for pages/feerecords/view.php's payments mini-table and
     * pages/payments/index.php when a fee record is picked.
     *
     * @param int $feerecordid
     * @return \stdClass[]
     */
    public static function get_for_feerecord(int $feerecordid): array {
        global $DB;

        $sql = "SELECT p.*, s.installmentnumber
                  FROM {financedep_feepayment} p
             LEFT JOIN {financedep_installmentsched} s ON s.id = p.installmentschedid
                 WHERE p.feerecordid = :feerecordid
              ORDER BY p.timecreated DESC";

        return array_values($DB->get_records_sql($sql, ['feerecordid' => $feerecordid]));
    }

    /**
     * Returns the most recently recorded payments/refunds across every
     * student, with student/category details joined in - for
     * pages/payments/index.php's default (no fee record picked yet)
     * view, same "recent activity" panel pattern as
     * installmentplan_manager::get_recent().
     *
     * @param int $limit
     * @return \stdClass[]
     */
    public static function get_recent(int $limit = 10): array {
        global $DB;

        $sql = "SELECT p.*, u.firstname, u.lastname, u.email,
                       f.academicyear, cc.name AS categoryname
                  FROM {financedep_feepayment} p
                  JOIN {financedep_feerecord} r ON r.id = p.feerecordid
                  JOIN {user} u ON u.id = r.studentid
                  JOIN {financedep_feestructure} f ON f.id = r.feestructureid
                  JOIN {course_categories} cc ON cc.id = f.categoryid
              ORDER BY p.timecreated DESC";

        $records = $DB->get_records_sql($sql, [], 0, $limit);

        foreach ($records as $record) {
            $record->fullname = fullname($record);
        }

        return array_values($records);
    }

    /**
     * The signed effect an ACTIVE payment row has (or had) on its fee
     * record's/installment's paidamount: positive for a PAYMENT,
     * negative for a REFUND. void_payment() applies the NEGATION of this
     * to reverse a row; record_payment()/record_refund() apply it
     * directly when first creating a row.
     *
     * @param \stdClass $payment a financedep_feepayment row
     * @return float
     */
    protected static function signed_effect(\stdClass $payment): float {
        $amount = (float) $payment->amount;

        return $payment->paymenttype === constants::PAYMENT_TYPE_REFUND ? -$amount : $amount;
    }

    /**
     * Generates a unique receipt number - see this class's docblock for
     * why this is system-generated rather than typed in by finance
     * staff.
     *
     * @return string
     */
    protected static function generate_receipt_number(): string {
        global $DB;

        do {
            $candidate = 'RCPT-' . date('Ymd') . '-' . strtoupper(substr(bin2hex(random_bytes(3)), 0, 6));
        } while ($DB->record_exists('financedep_feepayment', ['receiptnumber' => $candidate]));

        return $candidate;
    }

    /**
     * If $installmentschedid is non-zero, fetches and returns that
     * schedule row after confirming it actually belongs to
     * $feerecordid's own installment plan - a defensive check against a
     * form/page bug (or a tampered request) linking a payment to some
     * other student's installment. Returns null if $installmentschedid
     * is 0 (payment not linked to any specific installment - always
     * allowed, see this class's docblock).
     *
     * @param int $feerecordid
     * @param int $installmentschedid 0 for "not linked"
     * @return \stdClass|null
     */
    protected static function validate_installment_link(int $feerecordid, int $installmentschedid): ?\stdClass {
        global $DB;

        if ($installmentschedid === 0) {
            return null;
        }

        $sql = "SELECT s.*
                  FROM {financedep_installmentsched} s
                  JOIN {financedep_installmentplan} pl ON pl.id = s.installmentplanid
                 WHERE s.id = :installmentschedid AND pl.feerecordid = :feerecordid";

        $schedrow = $DB->get_record_sql($sql, [
            'installmentschedid' => $installmentschedid,
            'feerecordid' => $feerecordid,
        ]);

        if (!$schedrow) {
            throw new \moodle_exception('errorinstallmentnotforrecord', 'local_financedepartment');
        }

        return $schedrow;
    }

    /**
     * Applies a signed amount (positive = payment, negative = refund/
     * reversal) to one installment schedule row's paidamount, and
     * derives its status from the result - pending if nothing paid yet,
     * paid once paidamount reaches the row's own amount, otherwise
     * partiallypaid. Never writes INSTALLMENT_STATUS_OVERDUE - that
     * stays a live, computed-only display state, same as
     * installmentplan_manager's docblock already established for Step
     * 7.6.
     *
     * @param \stdClass $schedrow a financedep_installmentsched row
     * @param float $signedamount
     * @return void
     */
    protected static function apply_to_installment(\stdClass $schedrow, float $signedamount): void {
        global $DB;

        $newpaid = max(0, (float) $schedrow->paidamount + $signedamount);

        if ($newpaid <= 0) {
            $status = constants::INSTALLMENT_STATUS_PENDING;
        } else if ($newpaid >= (float) $schedrow->amount) {
            $status = constants::INSTALLMENT_STATUS_PAID;
        } else {
            $status = constants::INSTALLMENT_STATUS_PARTIALLY_PAID;
        }

        $DB->update_record('financedep_installmentsched', (object) [
            'id' => $schedrow->id,
            'paidamount' => $newpaid,
            'status' => $status,
            'timemodified' => time(),
        ]);
    }

    /**
     * Records a normal payment against a fee record: inserts an ACTIVE
     * financedep_feepayment row (paymenttype = payment), adds the amount
     * to the fee record's running paidamount via
     * feerecord_manager::add_payment_amount(), and - if
     * $data->installmentschedid is set - applies the same amount to that
     * installment's own paidamount/status. Logs a CREATE audit entry.
     *
     * @param \stdClass $data form data: feerecordid, installmentschedid (0 if none),
     *                        amount, paymentdate, paymentmethod, notes
     * @param int $recordedby
     * @return int the new payment id
     */
    public static function record_payment(\stdClass $data, int $recordedby): int {
        global $DB;

        $feerecordid = (int) $data->feerecordid;
        $installmentschedid = (int) ($data->installmentschedid ?? 0);
        $amount = (float) $data->amount;

        $DB->get_record('financedep_feerecord', ['id' => $feerecordid], '*', MUST_EXIST);
        $schedrow = self::validate_installment_link($feerecordid, $installmentschedid);

        $now = time();

        $payment = new \stdClass();
        $payment->feerecordid = $feerecordid;
        $payment->installmentschedid = $installmentschedid !== 0 ? $installmentschedid : null;
        $payment->paymenttype = constants::PAYMENT_TYPE_PAYMENT;
        $payment->amount = $amount;
        $payment->paymentdate = (int) $data->paymentdate;
        $payment->paymentmethod = !empty($data->paymentmethod) ? $data->paymentmethod : null;
        $payment->receiptnumber = self::generate_receipt_number();
        $payment->status = constants::PAYMENT_STATUS_ACTIVE;
        $payment->voidreason = null;
        $payment->voidedby = null;
        $payment->voidedat = null;
        $payment->notes = !empty($data->notes) ? $data->notes : null;
        $payment->recordedby = $recordedby;
        $payment->timecreated = $now;
        $payment->timemodified = $now;

        $id = $DB->insert_record('financedep_feepayment', $payment);

        feerecord_manager::add_payment_amount($feerecordid, $amount, $recordedby);
        if ($schedrow) {
            self::apply_to_installment($schedrow, $amount);
        }

        audit_manager::log(
            constants::AUDIT_ENTITY_FEEPAYMENT,
            $id,
            constants::AUDIT_ACTION_CREATE,
            null,
            ['feerecordid' => $feerecordid, 'amount' => $amount, 'receiptnumber' => $payment->receiptnumber],
            $recordedby
        );

        return $id;
    }

    /**
     * Records a refund against a fee record: inserts an ACTIVE
     * financedep_feepayment row (paymenttype = refund), and SUBTRACTS
     * the amount from the fee record's (and, if linked, the
     * installment's) running paidamount - the mirror image of
     * record_payment(). Direct/instant entry, not a request-and-approve
     * workflow - see this class's docblock. Logs a REFUND audit entry
     * (distinct from record_payment()'s CREATE, so a fee record's
     * history clearly shows which entries were money in vs money back
     * out).
     *
     * Callers must ensure $recordedby holds the `managerefunds`
     * capability - this method does not check it itself (see this
     * class's docblock).
     *
     * @param \stdClass $data form data: feerecordid, installmentschedid (0 if none),
     *                        amount, paymentdate, paymentmethod, notes
     * @param int $recordedby
     * @return int the new payment id
     */
    public static function record_refund(\stdClass $data, int $recordedby): int {
        global $DB;

        $feerecordid = (int) $data->feerecordid;
        $installmentschedid = (int) ($data->installmentschedid ?? 0);
        $amount = (float) $data->amount;

        $DB->get_record('financedep_feerecord', ['id' => $feerecordid], '*', MUST_EXIST);
        $schedrow = self::validate_installment_link($feerecordid, $installmentschedid);

        $now = time();

        $payment = new \stdClass();
        $payment->feerecordid = $feerecordid;
        $payment->installmentschedid = $installmentschedid !== 0 ? $installmentschedid : null;
        $payment->paymenttype = constants::PAYMENT_TYPE_REFUND;
        $payment->amount = $amount;
        $payment->paymentdate = (int) $data->paymentdate;
        $payment->paymentmethod = !empty($data->paymentmethod) ? $data->paymentmethod : null;
        $payment->receiptnumber = self::generate_receipt_number();
        $payment->status = constants::PAYMENT_STATUS_ACTIVE;
        $payment->voidreason = null;
        $payment->voidedby = null;
        $payment->voidedat = null;
        $payment->notes = !empty($data->notes) ? $data->notes : null;
        $payment->recordedby = $recordedby;
        $payment->timecreated = $now;
        $payment->timemodified = $now;

        $id = $DB->insert_record('financedep_feepayment', $payment);

        feerecord_manager::add_payment_amount($feerecordid, -$amount, $recordedby);
        if ($schedrow) {
            self::apply_to_installment($schedrow, -$amount);
        }

        audit_manager::log(
            constants::AUDIT_ENTITY_FEEPAYMENT,
            $id,
            constants::AUDIT_ACTION_REFUND,
            null,
            ['feerecordid' => $feerecordid, 'amount' => $amount, 'receiptnumber' => $payment->receiptnumber],
            $recordedby
        );

        return $id;
    }

    /**
     * Voids an ACTIVE payment or refund: reverses whichever effect it
     * had on the fee record's (and, if linked, the installment's)
     * paidamount via signed_effect(), then marks the row VOID. Idempotent
     * (silent no-op if the row is already VOID or does not exist as
     * ACTIVE) - matching installmentplan_manager::cancel()'s pattern.
     * Never deletes the row - see this class's docblock.
     *
     * Callers must ensure $voidedby holds the `managerefunds` capability
     * - this method does not check it itself (see this class's
     * docblock).
     *
     * @param int $id
     * @param string $voidreason required, always logged and stored
     * @param int $voidedby
     * @return void
     */
    public static function void_payment(int $id, string $voidreason, int $voidedby): void {
        global $DB;

        $before = $DB->get_record('financedep_feepayment', ['id' => $id], '*', MUST_EXIST);
        if ($before->status !== constants::PAYMENT_STATUS_ACTIVE) {
            return;
        }

        $now = time();
        $effect = self::signed_effect($before);

        feerecord_manager::add_payment_amount((int) $before->feerecordid, -$effect, $voidedby);
        if (!empty($before->installmentschedid)) {
            $schedrow = $DB->get_record('financedep_installmentsched', ['id' => $before->installmentschedid]);
            if ($schedrow) {
                self::apply_to_installment($schedrow, -$effect);
            }
        }

        $DB->update_record('financedep_feepayment', (object) [
            'id' => $id,
            'status' => constants::PAYMENT_STATUS_VOID,
            'voidreason' => $voidreason !== '' ? $voidreason : null,
            'voidedby' => $voidedby,
            'voidedat' => $now,
            'timemodified' => $now,
        ]);

        audit_manager::log(
            constants::AUDIT_ENTITY_FEEPAYMENT,
            $id,
            constants::AUDIT_ACTION_VOID,
            ['status' => constants::PAYMENT_STATUS_ACTIVE],
            ['status' => constants::PAYMENT_STATUS_VOID],
            $voidedby,
            $voidreason
        );
    }
}
